export const constrains = {

    NAMES_MAX_LENGTH: 32,
    NAMES_MIN_LENGTH: 4,

    POST_TITTLE_MAX_LENGTH: 64,
    POST_TITTLE_MIN_LENGTH: 16,

    POST_CONTENT_MAX_LENGTH: 8192,
    POST_CONTENT_MIN_LENGTH: 32,
}